### ISSUE TITLE
[Chrome 46 / Windows 10] Blockly UI does not completely close after loading in either blockly or coding UI

### ISSUE THREAD

**Issue by voiddreamer** [voiddreamer/BotLandTracking#1]
#### Reproduction
1. Have previously saved script
2. Open JavaScript UI or Blockly UI
3. Click Load
4. Close the previously opened UI
5. Open Blockly UI (Notice the Hardware pane did not show)
6. Close Blockly UI

#### Expected
All Blockly UI elements to close (Though the hardware pane did not open)

#### Happened
The Blockly UI did not completely close. All of the buttons were still visible.

#### Result
Refreshing the page is the only simple way to resume playing as the JavaScript UI and Blockly UI are no inaccessible.

#### Screenshot of result
![End Result](http://i.imgur.com/OvvWOvr.png)

#### Exception
![Exception](http://i.imgur.com/WJ7WZul.png)

#### Question
Could this in any way be related to the issue in the blockly UI not loading and refreshing on-the-fly?

**Comment by Adam13531** [comment]
I believe that this bug is caused by something bad that was saved to your local storage, although I'm not sure how that would happen. To help debug this further, can you do "JSON.stringify(localStorage)" and private-message it to me? Or obscure your password and publicly paste it here.

Also, small thing to note: if you stringify localStorage before I stream next, then the password won't matter as they're all invalid right now.

**Comment by voiddreamer** [comment]
````
"{"
blocklyXml ":"
undefined ","
botConfigXml ":" < xml xmlns = \"http://www.w3.org/1999/xhtml\"><block type=\"hardware_cloaking1\" x=\"75\" y=\"10\"><next><block type=\"hardware_shield2\"><next><block type=\"hardware_reflect2\"><next><block type=\"hardware_artillery2\"></block></next></block></next></block></next></block></xml>", "checkedEulaButton": "true", "debug": "undefined", "javaScriptCode": "update = function () {\n    // Hates everyone and cleans up the mess.\n    // \"This is why we can't have nice things\"\n    // Cloaking lv. 1, Shield lv. 2, Reflect lv. 2, Artillery lv. 2\n    closestEnemyBot = findClosestEnemyBot();\n    distanceToClosestEnemyBot = distanceTo(closestEnemyBot);\n    if (distanceToClosestEnemyBot <= 5) {\n        if (willArtilleryHit()) {\n            fireArtillery();\n        }\n    } else {\n        if (canCloak()) {\n            cloak();\n        }\n        if (canShield()) {\n            shield();\n        }\n        if (canReflect()) {\n            reflect();\n        }\n    }\n    if (willHarvest()) {\n        harvest();\n    }\n    closestResource = findClosestResource();\n    if (exists(closestResource)) {\n        moveTo(closestResource);\n    }\n    move();\n};", "lastUsedAccount": "voiddreamer", "lastUsedPassword": "7e8b96b93004"
}
````

**Comment by Adam13531** [comment]
I have a feeling that this is the same issue as https://github.com/voiddreamer/BotLandTracking/issues/4, which I'm going to comment on further (but in that issue, not this one).
